-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: master
    hooks:
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: end-of-file-fixer
-   repo: local
    hooks :
    -   id: git-lint
        name: git-lint
        description: Executes linting on python files diff.
        entry: git lint
        additional_dependencies: [git-lint]
        language: python
        types: [python]
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
