
[tool.uv]
default-groups = ["dev",]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pip>=25.1.1",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "ruff>=0.11.0",
    "uv>=0.7.8",
]

[tool.mypy]
ignore_missing_imports = true
strict = true
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
install_types = true
non_interactive = true
