#!/usr/local/bin/zsh
# This hook is sourced after a new virtualenv is activated.

# Set $PY_LINCHK_DIR to where you keep all your python linting/checking config
# when you `mkvirtualenv` it will simlink the files to the pwd 
[ -z "$PY_LINCHK_DIR" ] && exit 0 

for chk in $PY_LINCHK_DIR/*(D)
do
    ln -sv $chk .
done
